"""add task archive columns

Revision ID: ce85f5e97508
Revises: 0001_init
Create Date: 2025-12-12 21:37:46.416449

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ce85f5e97508'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_dependencies', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_dependencies', 'depends_on_task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_tag_links', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_tag_links', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_user_links', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_user_links', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_user_links', 'role',
               existing_type=postgresql.ENUM('ASSIGNEE', 'COLLABORATOR', name='taskuserrole'),
               nullable=False)
    op.add_column('tasks', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('archived_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_archived_by_user_id'), 'tasks', ['archived_by_user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['archived_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_archived_by_user_id'), table_name='tasks')
    op.drop_column('tasks', 'archived_by_user_id')
    op.drop_column('tasks', 'archived_at')
    op.alter_column('task_user_links', 'role',
               existing_type=postgresql.ENUM('ASSIGNEE', 'COLLABORATOR', name='taskuserrole'),
               nullable=True)
    op.alter_column('task_user_links', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_user_links', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_tag_links', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_tag_links', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_dependencies', 'depends_on_task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_dependencies', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
